export const SUPER_ADMIN_ROLE = "Super Admin";

export const SYSTEM_PERMISSIONS = [
  { key: "properties.read", name: "قراءة العروض", module: "properties" },
  { key: "properties.create", name: "إضافة عروض", module: "properties" },
  { key: "properties.update", name: "تعديل عروض", module: "properties" },
  { key: "properties.archive", name: "أرشفة عروض", module: "properties" },
  { key: "properties.restore", name: "إرجاع عروض مؤرشفة", module: "properties" },
  { key: "properties.delete", name: "حذف عروض", module: "properties" },
  { key: "properties.images.manage", name: "إدارة صور العروض", module: "properties" },
  { key: "properties.export", name: "تصدير وطباعة العروض", module: "properties" },
  { key: "rentals.read", name: "قراءة الإيجارات", module: "rentals" },
  { key: "rentals.create", name: "إضافة إيجارات", module: "rentals" },
  { key: "rentals.update", name: "تعديل إيجارات", module: "rentals" },
  { key: "rentals.archive", name: "أرشفة الإيجارات", module: "rentals" },
  { key: "rentals.restore", name: "إرجاع إيجارات مؤرشفة", module: "rentals" },
  { key: "rentals.delete", name: "حذف إيجارات", module: "rentals" },
  { key: "rentals.images.manage", name: "إدارة صور الإيجارات", module: "rentals" },
  { key: "rentals.followups.read", name: "عرض متابعات الإيجارات", module: "rentals" },
  { key: "rentals.followups.create", name: "إضافة متابعة إيجار", module: "rentals" },
  { key: "rentals.followups.update", name: "تعديل متابعة إيجار", module: "rentals" },
  { key: "rentals.followups.delete", name: "حذف متابعة إيجار", module: "rentals" },
  { key: "users.read", name: "قراءة المستخدمين", module: "users" },
  { key: "users.create", name: "إضافة مستخدمين", module: "users" },
  { key: "users.update", name: "تعديل مستخدمين", module: "users" },
  { key: "users.delete", name: "حذف مستخدمين", module: "users" },
  { key: "roles.read", name: "قراءة الأدوار", module: "roles" },
  { key: "roles.create", name: "إضافة أدوار", module: "roles" },
  { key: "roles.update", name: "تعديل أدوار", module: "roles" },
  { key: "roles.delete", name: "حذف أدوار", module: "roles" },
  { key: "settings.read", name: "قراءة الإعدادات", module: "settings" },
  { key: "settings.update", name: "تعديل الإعدادات", module: "settings" },
  { key: "locations.manage", name: "إدارة المحافظات والمناطق", module: "locations" },
  { key: "audit.read", name: "عرض سجل التغييرات", module: "audit" },
  { key: "security.change_pin", name: "تغيير رمز PIN", module: "security" },
  { key: "backups.read", name: "عرض النسخ الاحتياطية", module: "backups" },
  { key: "backups.create", name: "إنشاء نسخة احتياطية", module: "backups" },
  { key: "backups.restore", name: "استرجاع نسخة احتياطية", module: "backups" },
  { key: "backups.schedule", name: "جدولة النسخ الاحتياطي بالبريد", module: "backups" },
  { key: "followups.read", name: "عرض المتابعات", module: "followups" },
  { key: "followups.create", name: "إضافة متابعة", module: "followups" },
  { key: "followups.update", name: "تعديل متابعة", module: "followups" },
  { key: "followups.delete", name: "حذف متابعة", module: "followups" }
,  { key: "customers.read", name: "قراءة العملاء", module: "customers" },
  { key: "customers.create", name: "إضافة العملاء", module: "customers" },
  { key: "customers.update", name: "تعديل العملاء", module: "customers" },
  { key: "requests.read", name: "قراءة طلبات العملاء", module: "requests" },
  { key: "requests.create", name: "إضافة طلبات العملاء", module: "requests" },
  { key: "requests.update", name: "تعديل طلبات العملاء", module: "requests" },
  { key: "documents.read", name: "قراءة مستندات العملاء", module: "documents" },
  { key: "documents.manage", name: "إدارة مستندات العملاء", module: "documents" },
  { key: "contracts.read", name: "قراءة العقود", module: "contracts" },
  { key: "contracts.manage", name: "إدارة العقود", module: "contracts" },
  { key: "contract_templates.manage", name: "إدارة قوالب العقود", module: "contracts" },
] as const;
