<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import AppLayout from "../layouts/AppLayout.vue";
import RentalForm from "../components/rentals/RentalForm.vue";
import * as rentals from "../services/rentals.service";
import { getErrorMessage } from "../services/api.service";
import { useLocations } from "../composables/useLocations";
import { useSnackbar } from "../composables/useSnackbar";
import type { RentalForm as RentalFormType, RentalRecord } from "../types";
const route = useRoute(); const router = useRouter(); const { loadLocations } = useLocations(); const { notifyError, notifySuccess } = useSnackbar();
function empty(): RentalFormType { return { name: "", property_type: "house", rent_price: "", rent_period: "monthly", area_value: "", area_unit: "متر", floors_count: null, rooms_count: null, bathrooms_count: null, amenities: {}, other_details: "", governorate_id: null, district_id: null, neighborhood_id: null, governorate: "", district: "", neighborhood: "", address_details: "", owner_name: "", owner_phone: "", owner_notes: "", status: "available", is_negotiable: false, notes: "" }; }
function toForm(item: RentalRecord): RentalFormType { return { name: item.name ?? "", property_type: item.property_type, rent_price: item.rent_price, rent_period: item.rent_period, area_value: item.area_value, area_unit: item.area_unit, floors_count: item.floors_count, rooms_count: item.rooms_count, bathrooms_count: item.bathrooms_count, amenities: item.amenities ?? {}, other_details: item.other_details ?? "", governorate_id: item.governorate_id, district_id: item.district_id, neighborhood_id: item.neighborhood_id, governorate: item.governorate ?? "", district: item.district ?? "", neighborhood: item.neighborhood ?? "", address_details: item.address_details ?? "", owner_name: item.owner_name, owner_phone: item.owner_phone, owner_notes: item.owner_notes ?? "", status: item.status, is_negotiable: item.is_negotiable, notes: item.notes ?? "" }; }
const form = ref<RentalFormType>(empty()); const editingId = ref<number | null>(null); const saving = ref(false); const formRef = ref<{ validate: () => Promise<boolean> } | null>(null); const isEditing = computed(() => editingId.value !== null);
async function save() { if (!(await formRef.value?.validate())) { notifyError("تحقق من الحقول المطلوبة."); return; } saving.value = true; const payload = { ...form.value, rent_price: Number(form.value.rent_price), area_value: Number(form.value.area_value), floors_count: form.value.floors_count === null ? null : Number(form.value.floors_count), rooms_count: form.value.rooms_count === null ? null : Number(form.value.rooms_count), bathrooms_count: form.value.bathrooms_count === null ? null : Number(form.value.bathrooms_count) }; try { if (editingId.value) { await rentals.updateRental(editingId.value, payload); notifySuccess("تم تحديث العرض الإيجاري."); await router.push('/rentals'); } else { const created = await rentals.createRental(payload); notifySuccess("تمت إضافة العرض الإيجاري."); await router.push(`/rentals/${created.id}/edit`); } } catch (e) { notifyError(getErrorMessage(e)); } finally { saving.value = false; } }
onMounted(async () => { await loadLocations(); const id = Number(route.params.id); if (id) { try { const item = await rentals.getRental(id); form.value = toForm(item); editingId.value = id; } catch (e) { notifyError(getErrorMessage(e)); await router.replace('/rentals'); } } });
</script>
<template><AppLayout :title="isEditing ? 'تعديل عرض إيجاري' : 'إضافة عرض إيجاري'" subtitle="نموذج مستقل للعروض الإيجارية."><RentalForm ref="formRef" v-model="form" :editing="isEditing" :saving="saving" :rental-id="editingId" @submit="save" @cancel="router.push('/rentals')" /></AppLayout></template>
